import Provider from '@/components/Provider'
import './globals.css'
import Nav from '@/components/Nav'

export const metadata = {
  title: 'Promptia',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressContentEditableWarning>
       <Provider>
          <main className='app'>
          <Nav/>
        {children}
          </main>
          </Provider>
        </body>
    </html>
  )
}
